name = "pulse-data-worker"
main = "index.js"
compatibility_date = "2026-03-17"
workers_dev = true
preview_urls = false

[vars]
ENVIRONMENT = "production"
DATA_REFRESH_TTL_SECONDS = "14400"
DATA_STALE_TTL_SECONDS = "86400"

[triggers]
crons = ["0 */4 * * *"]

[[kv_namespaces]]
binding = "METRICS_CACHE"
id = "f950b17f36a447dca7bb339cba8818de"
preview_id = "4c09f1919ccf49169348eab62c48f643"
